// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';
import { selectSettingsTheme } from './settings-fixtures';
import { installSupplyWallet, setSupplyWalletChain } from './supply-fixtures';

for (const theme of ['Light', 'Dark']) test(`${theme} Bridge side pickers show separate token and network columns with only supported endpoints`, async ({ page }) => {
  await installSupplyWallet(page); await page.goto('/app');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await selectSettingsTheme(page, theme);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Environment', exact: true })).toHaveText('Testnet');
  await page.getByRole('button', { name: 'Add bridge', exact: true }).click();
  const card = page.locator('.build-flow-surface .composer-card');
  const source = card.getByRole('button', { name: 'Configure source asset', exact: true });
  const destination = card.getByRole('button', { name: 'Configure destination asset', exact: true });
  await card.getByRole('textbox').fill('2.5');
  await expect(source).toHaveAttribute('title', 'USDC on Base Sepolia');
  await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum Sepolia');
  await expect(card.locator('.composer-metadata')).toHaveText('Router');
  await expect(card.locator('.composer-chain, .composer-bridge-network-pill, .composer-bridge-identities')).toHaveCount(0);
  await expect(card).not.toContainText('Sepolia');
  await expect(card.locator('.composer-value-arrow svg')).toBeVisible();
  await card.getByRole('button', { name: 'Show fiat amount first (estimate unavailable)', exact: true }).first().click();
  for (const box of await card.locator('.composer-amount-box').all()) {
    const primary = (await box.locator('.composer-primary-fiat').boundingBox())!, pill = (await box.locator('.composer-token-pill').boundingBox())!;
    expect(primary.x + primary.width).toBeLessThan(pill.x);
  }
  await card.getByRole('button', { name: 'Show token amount first', exact: true }).first().click();
  await card.getByRole('button', { name: 'Review amount', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeEnabled();
  for (const [side, current, options] of [
    ['source', 'Base Sepolia', ['Base Sepolia', 'Solana Devnet']],
    ['destination', 'Arbitrum Sepolia', ['Arbitrum Sepolia', 'Solana Devnet']],
  ] as const) {
    const trigger = side === 'source' ? source : destination, label = side === 'source' ? 'Source' : 'Destination';
    await trigger.click();
    const panel = page.getByRole('region', { name: `${label} bridge picker`, exact: true });
    const tokens = panel.getByRole('region', { name: `${label} token picker`, exact: true });
    const networks = panel.getByRole('region', { name: `${label} network picker`, exact: true });
    const token = tokens.getByRole('radio', { name: 'USDC', exact: true });
    const network = networks.getByRole('button', { name: current, exact: true });
    await expect(trigger).toHaveAttribute('aria-expanded', 'true');
    await expect(tokens).toBeVisible(); await expect(networks).toBeVisible();
    await expect(token).toBeChecked(); await expect(token).toBeFocused();
    await expect(network).toHaveAttribute('aria-pressed', 'true');
    await expect(tokens.locator('[data-selected] .composer-stock-check')).toBeVisible();
    await expect(network.locator('.composer-stock-check')).toBeVisible();
    await expect(tokens.locator('[data-selected]')).not.toHaveCSS('border-color', 'rgba(0, 0, 0, 0)');
    expect(await tokens.getByRole('radio').evaluateAll(elements => elements.map(element => (element as HTMLInputElement).value))).toEqual(['USDC']);
    expect(await networks.getByRole('button').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual([...options]);
    await expect(networks.getByRole('button', { name: 'Solana Devnet', exact: true })).toBeDisabled();
    await expect(networks.getByRole('button', { name: 'Solana', exact: true })).toHaveCount(0);
    await expect(tokens.getByRole('button')).toHaveCount(0); await expect(networks.getByRole('radio')).toHaveCount(0);
    await expect(panel.locator('.composer-token-pill, .composer-bridge-network-pill, .composer-bridge-picker-row, .composer-bridge-picker-choices')).toHaveCount(0);
    await expect(panel.getByRole('combobox')).toHaveCount(0);
    await expect(panel).toBeInViewport({ ratio: .99 });
    const bounds = (await panel.boundingBox())!, cardBounds = (await card.boundingBox())!;
    expect(bounds.x).toBeGreaterThan(cardBounds.x + cardBounds.width);
    const tokenBox = (await tokens.boundingBox())!, networkBox = (await networks.boundingBox())!;
    expect(networkBox.x).toBeGreaterThan(tokenBox.x + tokenBox.width);
    expect(Math.abs(networkBox.y - tokenBox.y)).toBeLessThan(1);
    await expect(networks).toHaveCSS('border-left-width', '1px');
    const spacing = await panel.evaluate(element => ({ padding: parseFloat(getComputedStyle(element).paddingRight), gap: parseFloat(getComputedStyle(element.querySelector('.composer-bridge-picker-columns')!).columnGap) }));
    expect(spacing.padding).toBeLessThanOrEqual(theme === 'Light' ? 8 : 5); expect(spacing.gap).toBeLessThanOrEqual(theme === 'Light' ? 8 : 6);
    await expect(tokens.locator('.composer-network-badge')).toHaveCount(0);
    await expect(trigger.getByRole('img', { name: `${current} network`, exact: true })).toBeVisible();
    await tokens.locator('label').click();
    await expect(token).toBeChecked(); await expect(network).toHaveAttribute('aria-pressed', 'true');
    await expect(source).toHaveAttribute('title', 'USDC on Base Sepolia');
    await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum Sepolia');
    await network.press('Enter');
    await expect(tokens).toBeVisible(); await expect(networks).toBeVisible();
    await expect(token).toBeChecked(); await expect(network).toHaveAttribute('aria-pressed', 'true');
    await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeEnabled();
    await network.press('Escape'); await expect(panel).toHaveCount(0); await expect(trigger).toBeFocused();
  }
  await setSupplyWalletChain(page, '0x2105');
  await expect(source).toHaveAttribute('title', 'USDC on Base');
  await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum');
  await expect(card.getByRole('textbox')).toHaveValue('2.5');
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeDisabled();
  await expect(card.getByRole('button', { name: 'Review amount', exact: true })).toBeEnabled();
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
  await source.click();
  const panel = page.getByRole('region', { name: 'Source bridge picker', exact: true });
  await expect(panel.getByRole('button', { name: 'Solana', exact: true })).toBeDisabled();
  await expect(panel.getByRole('button', { name: 'Solana Devnet', exact: true })).toHaveCount(0);
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 }); await expect(panel).toBeInViewport({ ratio: .99 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    if (width !== 320) await page.screenshot({ path: `.tmp/bridge-columns-${theme.toLowerCase()}-${width}.png`, fullPage: true });
  }
  await page.locator('.canvas-head h2').click(); await expect(panel).toHaveCount(0);
  await source.click();
  await panel.getByRole('button', { name: 'Base', exact: true }).press('Escape');
  await expect(panel).toHaveCount(0); await expect(source).toBeFocused();
});

test('Bridge wallet network changes keep supported drafts aligned and require fresh Review / Apply', async ({ page }) => {
  await installSupplyWallet(page); await page.goto('/app');
  await setSupplyWalletChain(page, '0x14a34');
  await page.getByRole('button', { name: 'Add bridge', exact: true }).click();
  const card = page.locator('.build-flow-surface .composer-card');
  const source = card.getByRole('button', { name: 'Configure source asset', exact: true });
  const destination = card.getByRole('button', { name: 'Configure destination asset', exact: true });
  const assertOptions = async (side: 'source' | 'destination', current: string) => {
    await card.getByRole('button', { name: `Configure ${side} asset`, exact: true }).click();
    const networks = page.getByRole('region', { name: `${side === 'source' ? 'Source' : 'Destination'} network picker`, exact: true });
    const solana = current.includes('Sepolia') ? 'Solana Devnet' : 'Solana';
    expect(await networks.getByRole('button').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual([current, solana]);
    await expect(networks.getByRole('button', { name: solana, exact: true })).toBeDisabled();
    await expect(networks.getByRole('button', { name: current, exact: true })).toHaveAttribute('aria-pressed', 'true');
    await page.getByRole('button', { name: 'Hide bridge picker', exact: true }).click();
  };
  await card.getByRole('textbox').fill('2.5');
  await card.getByRole('button', { name: 'Review amount', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeEnabled();
  await setSupplyWalletChain(page, '0x2105');
  await expect(source).toHaveAttribute('title', 'USDC on Base'); await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum');
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Simulate fees', exact: true })).toBeDisabled();
  await assertOptions('source', 'Base'); await assertOptions('destination', 'Arbitrum');
  await expect(card.getByRole('textbox')).toHaveValue('2.5');
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
  await card.getByRole('button', { name: 'Review amount', exact: true }).click();
  await card.getByRole('button', { name: 'Apply amount', exact: true }).click();
  await card.getByRole('button', { name: 'Advanced Settings', exact: true }).click();
  const form = page.getByRole('form', { name: 'Edit cross-chain bridge', exact: true });
  await expect(form.getByLabel('Cross-chain network', { exact: true })).toBeDisabled();
  expect(await form.getByLabel('Cross-chain network', { exact: true }).locator('option').allTextContents()).toEqual(['Mainnet (real funds)']);
  await expect(form.getByLabel('Cross-chain source chain', { exact: true })).toHaveValue('Base');
  await expect(form.getByLabel('Cross-chain destination chain', { exact: true })).toHaveValue('Arbitrum');
  const revision = await page.locator('.summary-bar').getAttribute('data-workflow-revision');
  await source.click();
  const openNetworks = page.getByRole('region', { name: 'Source network picker', exact: true });
  await expect(openNetworks.getByRole('button', { name: 'Solana', exact: true })).toBeDisabled();
  await setSupplyWalletChain(page, '0x14a34');
  await expect(openNetworks.getByRole('button', { name: 'Base Sepolia', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(openNetworks.getByRole('button', { name: 'Solana Devnet', exact: true })).toBeDisabled();
  await expect(openNetworks.getByRole('button', { name: 'Base', exact: true })).toHaveCount(0);
  await expect(openNetworks.getByRole('button', { name: 'Solana', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Hide bridge picker', exact: true }).click();
  await expect(source).toHaveAttribute('title', 'USDC on Base Sepolia'); await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum Sepolia');
  await expect(form.getByLabel('Cross-chain source chain', { exact: true })).toHaveValue('Base Sepolia');
  await expect(form.getByLabel('Cross-chain destination chain', { exact: true })).toHaveValue('Arbitrum Sepolia');
  expect(await form.getByLabel('Cross-chain network', { exact: true }).locator('option').allTextContents()).toEqual(['Testnet (test USDC)']);
  await assertOptions('source', 'Base Sepolia'); await assertOptions('destination', 'Arbitrum Sepolia');
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', revision!);
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeDisabled();
  await card.getByRole('button', { name: 'Review amount', exact: true }).click();
  await card.getByRole('button', { name: 'Apply amount', exact: true }).click();
  await expect(form.getByLabel('Cross-chain network', { exact: true })).toHaveValue('testnet');
  await setSupplyWalletChain(page, '0x2105');
  await card.getByRole('button', { name: 'Review amount', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeEnabled();
  await setSupplyWalletChain(page, '0x14a34');
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toBeDisabled();
  await card.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Simulate fees', exact: true })).toBeEnabled();
  await expect(source).toHaveAttribute('title', 'USDC on Base Sepolia');
  await expect(destination).toHaveAttribute('title', 'USDC on Arbitrum Sepolia');
  await expect(card.getByRole('textbox')).toHaveValue('2.5');
  await form.getByRole('button', { name: 'Review bridge change', exact: true }).click();
  await setSupplyWalletChain(page, '0x89');
  await expect(form.getByLabel('Cross-chain network', { exact: true })).toHaveValue('');
  await expect(form.getByLabel('Cross-chain source chain', { exact: true })).toHaveValue('');
  await expect(form.getByLabel('Cross-chain destination chain', { exact: true })).toHaveValue('');
  await expect(form.getByRole('button', { name: 'Review bridge change', exact: true })).toBeDisabled();
  await expect(page.getByRole('region', { name: 'Workflow edit review', exact: true })).toHaveCount(0);
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toHaveCount(0);
  await setSupplyWalletChain(page, '0x14a34');
  await expect(form.getByLabel('Cross-chain network', { exact: true })).toHaveValue('testnet');
  await expect(card.getByRole('button', { name: 'Apply amount', exact: true })).toHaveCount(0);
});
