// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';
const recipient = '0x1111111111111111111111111111111111111111';
test('BUILD-011C-1 canvas and chat propose the same graph and MOCKED run reconciles the LP', async ({ page }) => {
  await page.goto('/');
  await page.getByText('Advanced action setup', { exact: true }).click();
  await page.getByText('Base → Arbitrum → Uniswap v3 position', { exact: true }).click();
  const inspector = page.getByRole('form', { name: 'Compose cross-chain liquidity' });
  await expect(inspector).toBeVisible();
  await inspector.getByLabel('Composition source quantity (USDC)').fill('100');
  await inspector.getByRole('button', { name: 'Review cross-chain composition' }).click();
  await page.getByRole('button', { name: 'Apply proposal' }).click();
  const review = page.getByRole('region', { name: 'Deterministic review findings' });
  await expect(review).toContainText('Base → Arbitrum liquidity composition');
  await expect(page.getByText('Calculate destination split')).toBeVisible();
  await expect(page.getByText('Mint Uniswap v3 position')).toBeVisible();
  const canvasIR = await review.locator('[data-workflow-ir]').textContent();
  expect(canvasIR).toContain('"outputId": "swap-input"');
  await page.getByRole('button', { name: 'Simulate', exact: true }).click();
  const panel = page.getByRole('region', { name: 'Cross-chain liquidity composition' });
  await panel.getByRole('button', { name: 'Generate MOCKED chained simulation' }).click();
  await expect(panel).toContainText('Estimated bridge output:');
  await expect(panel).toContainText('pool swap fee');
  await page.getByRole('button', { name: 'Execute', exact: true }).click();
  await panel.getByRole('button', { name: 'Submit MOCKED bridge' }).click();
  await panel.getByRole('button', { name: 'Reconcile MOCKED destination balance' }).click();
  await expect(panel).toContainText('Reconciled destination output:');
  await panel.getByRole('button', { name: 'Review actual amount and new Manifest' }).click();
  await panel.getByRole('button', { name: 'Reconcile MOCKED destination swap' }).click();
  await panel.getByRole('button', { name: 'Submit MOCKED liquidity mint' }).click();
  await panel.getByRole('button', { name: 'Reconcile MOCKED LP position' }).click();
  await expect(panel).toContainText('Reconciled position NFT #77');
  await expect(panel).toContainText('MOCKED Evidence Bundle:');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Review composition change' }).click();
  await page.getByRole('button', { name: 'Dismiss' }).click();
  // A fresh chat proposal remains typed and reviewable; no model or arbitrary calldata is used.
  const chat = `bridge 100 USDC from Base to Arbitrum via LI.FI and create Uniswap liquidity ticks -200100 to -199900 recipient ${recipient}`;
  await page.locator('#mock-prompt').fill(chat);
  await page.getByRole('button', { name: 'Send' }).click();
  await expect(page.getByText('AUTHOR_CROSS_CHAIN_LIQUIDITY · base revision')).toBeVisible();
  expect(canvasIR).toContain('"actionType": "asset.liquidity.uniswap-v3"');
});
