// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';
test('BUILD-011C-2 shows partial bridge success and manual recovery after destination swap revert', async ({ page }) => {
  await page.goto('/');
  await page.getByText('Advanced action setup', { exact: true }).click();
  await page.getByText('Base → Arbitrum → Uniswap v3 position', { exact: true }).click();
  const inspector = page.getByRole('form', { name: 'Compose cross-chain liquidity' });
  await inspector.getByLabel('Composition source quantity (USDC)').fill('100');
  await inspector.getByRole('button', { name: 'Review cross-chain composition' }).click();
  await page.getByRole('button', { name: 'Apply proposal' }).click();
  await page.getByRole('button', { name: 'Execute', exact: true }).click();
  const panel = page.getByRole('region', { name: 'Cross-chain liquidity composition' });
  await panel.getByLabel('Deterministic outcome').selectOption('SWAP_REVERT');
  await panel.getByRole('button', { name: 'Generate MOCKED chained simulation' }).click();
  await panel.getByRole('button', { name: 'Submit MOCKED bridge' }).click();
  await panel.getByRole('button', { name: 'Reconcile MOCKED destination balance' }).click();
  await panel.getByRole('button', { name: 'Review actual amount and new Manifest' }).click();
  await panel.getByRole('button', { name: 'Reconcile MOCKED destination swap' }).click();
  const recovery = panel.getByRole('region', { name: 'Cross-chain recovery' });
  await expect(recovery).toContainText('PARTIALLY COMPLETED');
  await expect(recovery).toContainText('99.25 USDC');
  await expect(recovery).toContainText('destination-swap');
  await expect(recovery).toContainText('COMPENSATE: NOT_SUPPORTED');
  await expect(recovery).toContainText('MANUAL: AVAILABLE');
  await expect(recovery).toContainText('does not revoke');
  await recovery.getByRole('button', { name: 'Stop automatic continuation' }).click();
  await expect(recovery).toContainText('Manual intervention selected. Local execution paused');
  await expect(panel).toContainText('MOCKED Evidence Bundle:');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await expect(page.locator('.flow-card').filter({ hasText: 'Bridge USDC' })).toContainText('Runtime: Completed');
  await expect(page.locator('.flow-card').filter({ hasText: 'Swap selected USDC for WETH' })).toContainText('Runtime: Failed');
});
