// SPDX-License-Identifier: AGPL-3.0-only
/**
 * BUILD-AUTOMATION-002 browser suite: the owner's injected wallets, a WebAuthn virtual authenticator, the bearer-only dispatches (with the
 * deterministic test clock) and the MOCKED loopback chain harness's control calls. Owner keys exist only in this test process's memory
 * (never written, logged or committed); the per-run dispatch token and the disposable session-signer directory under /tmp are generated by
 * playwright.config.ts. Nothing here reaches a public chain.
 */
import { erc7710 } from '@defi-workflow-engine/reference-compiler';
import { memorySignerProvider } from '@defi-workflow-engine/reference-executor';
import { test as base, type BrowserContext, type CDPSession, type Page } from '@playwright/test';
import { E2E_APP_PORT } from './app-origin';

/** WebAuthn refuses IP-address RP ids, so this journey visits the same app server on `localhost` (FLOFI_PASSKEY_ORIGIN). */
export const DELEGATION_ORIGIN = `http://localhost:${E2E_APP_PORT}`;
const HARNESS = 'http://127.0.0.1:8560';

/**
 * The suite's network guard (`fixtures.ts`), bound to this journey's origin: anything but the app origin is aborted and fails the test, and
 * WebSockets, popups and service workers are refused. The MOCKED chains are reached only by the app server and this test process.
 */
export const test = base.extend<{ context: BrowserContext; page: Page }>({
  context: async ({ browser }, use) => {
    const context = await browser.newContext({ baseURL: DELEGATION_ORIGIN, serviceWorkers: 'block', viewport: { width: 1440, height: 900 }, colorScheme: 'light',
      reducedMotion: 'reduce', locale: 'en-US', timezoneId: 'Europe/Lisbon' });
    const unexpected: string[] = [];
    let pages = 0;
    context.on('page', () => { pages += 1; if (pages > 1) unexpected.push('UNGUARDED_POPUP'); });
    context.on('serviceworker', () => unexpected.push('SERVICE_WORKER'));
    await context.route('**/*', async route => {
      let allowed = false;
      try { allowed = new URL(route.request().url()).origin === DELEGATION_ORIGIN; } catch { /* invalid URL is forbidden */ }
      if (allowed) await route.continue(); else { unexpected.push(route.request().url()); await route.abort('blockedbyclient'); }
    });
    await context.routeWebSocket('**/*', async route => { unexpected.push(`WEBSOCKET:${route.url()}`); await route.close(); });
    try {
      await use(context);
      if (unexpected.length) throw new Error(`Unexpected network attempts: ${unexpected.join(', ')}`);
    } finally { await context.close(); }
  },
  page: async ({ context }, use) => { const page = await context.newPage(); try { await use(page); } finally { await page.close(); } },
});
export { expect } from '@playwright/test';

export function assertDelegationHarness(): void {
  if (process.env.GRYLOO_DELEGATION_E2E !== 'MOCKED_LOOPBACK_ONLY' || !process.env.FLOFI_E2E_DELEGATION_DISPATCH_TOKEN
    || !process.env.FLOFI_E2E_DELEGATED_SIGNER_DIR?.startsWith('/tmp/flofi-delegation-e2e-')) throw new Error('DELEGATION_HARNESS_REQUIRED');
}
export async function chainControl<T = unknown>(method: string, params: unknown[] = []): Promise<T> {
  const response = await fetch(`${HARNESS}/control`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ method, params }) });
  const body = await response.json() as { result?: T; error?: { message: string } };
  if (body.error) throw new Error(body.error.message);
  return body.result as T;
}
/** One drain of delegated-execution work at `at` (the same test clock as the automation scheduler). */
export async function delegationDispatch(at?: Date): Promise<{ status: number; body: Record<string, unknown> }> {
  const response = await fetch(`${DELEGATION_ORIGIN}/api/delegation/dispatch`, { method: 'POST', headers: {
    authorization: `Bearer ${process.env.FLOFI_E2E_DELEGATION_DISPATCH_TOKEN!}`, ...at ? { 'x-flofi-automation-now': at.toISOString() } : {} } });
  return { status: response.status, body: await response.json() as Record<string, unknown> };
}

/** A user-verifying platform authenticator (CTAP2, resident keys) attached to this page through Chrome DevTools. */
export async function virtualAuthenticator(page: Page): Promise<{ cdp: CDPSession; id: string; credentials: () => Promise<number> }> {
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('WebAuthn.enable');
  const { authenticatorId } = await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true,
    hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  return { cdp, id: authenticatorId, credentials: async () => (await cdp.send('WebAuthn.getCredentials', { authenticatorId })).credentials.length };
}

// An independent EIP-712 encoder over the JSON a wallet receives (`eth_signTypedData_v4`): the browser-signed bytes must be what the
// server verifies, without reusing the server's own hashing.
type Field = { name: string; type: string };
type TypedData = { types: Record<string, Field[]>; domain: Record<string, unknown>; primaryType: string; message: Record<string, unknown> };
function typedDataDigest(td: TypedData): string {
  const deps = (name: string, found = new Set<string>()): Set<string> => {
    if (found.has(name) || !td.types[name]) return found;
    found.add(name);
    for (const f of td.types[name]!) deps(f.type.replace(/\[\]$/, ''), found);
    return found;
  };
  const encodeType = (name: string) => [name, ...[...deps(name)].filter(n => n !== name).sort()].map(n => `${n}(${td.types[n]!.map(f => `${f.type} ${f.name}`).join(',')})`).join('');
  const keccak = (bytes: Uint8Array | string) => erc7710.bytesOf(erc7710.keccakHex(bytes));
  const enc = (type: string, value: unknown): Uint8Array => {
    if (type.endsWith('[]')) return keccak(Uint8Array.from((value as unknown[]).flatMap(v => [...enc(type.slice(0, -2), v)])));
    if (td.types[type]) return hashStruct(type, value as Record<string, unknown>);
    if (type === 'string') return keccak(value as string);
    if (type === 'bytes') return keccak(erc7710.bytesOf(value as string));
    if (type === 'address') return erc7710.bytesOf('0x' + (value as string).slice(2).toLowerCase().padStart(64, '0'));
    if (type === 'bytes32') return erc7710.bytesOf(value as string);
    if (type === 'uint256') return erc7710.word(BigInt(value as string | number));
    throw new Error(`EIP712_TYPE_UNSUPPORTED:${type}`);
  };
  const hashStruct = (name: string, value: Record<string, unknown>) =>
    keccak(Uint8Array.from([...keccak(encodeType(name)), ...td.types[name]!.flatMap(f => [...enc(f.type, value[f.name])])]));
  return erc7710.keccakHex(Uint8Array.from([0x19, 0x01, ...hashStruct('EIP712Domain', td.domain), ...hashStruct(td.primaryType, td.message)]));
}

const keys = memorySignerProvider();
/** The owner's EVM account (a MetaMask smart account on the chain double): `personal_sign` for sign-in and EIP-712 for enrollment. */
export async function createDelegationOwner() {
  const key = await keys.create('eip155');
  const sign = async (digest: string) => {
    const s = await keys.signEvmDigest(key.ref, erc7710.bytesOf(digest));
    return '0x' + s.r.toString(16).padStart(64, '0') + s.s.toString(16).padStart(64, '0') + (s.yParity + 27).toString(16);
  };
  return { address: key.address,
    personalSign: (message: string) => { const bytes = new TextEncoder().encode(message);
      return sign(erc7710.keccakHex(Uint8Array.from([...new TextEncoder().encode(`\x19Ethereum Signed Message:\n${bytes.length}`), ...bytes]))); },
    signTypedData: (json: string) => sign(typedDataDigest(JSON.parse(json) as TypedData)) };
}
const utf8 = (param: unknown) => typeof param === 'string' && /^0x(?:[0-9a-fA-F]{2})*$/.test(param) ? Buffer.from(param.slice(2), 'hex').toString('utf8') : String(param);

/**
 * The injected EIP-1193 wallet. It records every request; `eth_signTypedData_v4` (Credential enrollment) and `eth_sendTransaction` (the
 * owner's own revocation, sent to the chain double) are the only signing methods it serves.
 */
export async function installDelegationEvmWallet(page: Page, owner: Awaited<ReturnType<typeof createDelegationOwner>>) {
  await page.exposeFunction('flofiDelegationWallet', async (method: string, params: unknown[]) => {
    if (method === 'personal_sign') return owner.personalSign(utf8(params[0]));
    if (method === 'eth_signTypedData_v4') return owner.signTypedData(String(params[1]));
    if (method === 'eth_sendTransaction') { const tx = params[0] as { from: string; to: string; data: string }; return chainControl('MOCK_ownerSend', [tx.from, tx.to, tx.data]); }
    throw new Error('MOCK_WALLET_METHOD_DENIED');
  });
  await page.addInitScript(({ account }) => {
    type Listener = (...args: unknown[]) => void;
    const listeners = new Map<string, Set<Listener>>(), state = { account, chain: '0x14a34', requests: [] as string[] };
    const w = window as unknown as { ethereum: unknown; flofiDelegationRequests: string[]; flofiDelegationWallet: (method: string, params: unknown[]) => Promise<unknown> };
    w.flofiDelegationRequests = state.requests;
    w.ethereum = {
      on(event: string, listener: Listener) { if (!listeners.has(event)) listeners.set(event, new Set()); listeners.get(event)!.add(listener); },
      removeListener(event: string, listener: Listener) { listeners.get(event)?.delete(listener); },
      request: async (input: { method: string; params?: unknown[] }) => {
        state.requests.push(input.method);
        const params = input.params ?? [];
        if (input.method === 'eth_accounts' || input.method === 'eth_requestAccounts') return [state.account];
        if (input.method === 'eth_chainId') return state.chain;
        const from = String(input.method === 'eth_sendTransaction' ? (params[0] as { from?: string }).from : input.method === 'personal_sign' ? params[1] : params[0]).toLowerCase();
        if (['personal_sign', 'eth_signTypedData_v4', 'eth_sendTransaction'].includes(input.method)) {
          if (from !== state.account) throw Object.assign(new Error('Unauthorized account'), { code: 4100 });
          return w.flofiDelegationWallet(input.method, params);
        }
        throw new Error('MOCK_WALLET_METHOD_DENIED');
      },
    };
  }, { account: owner.address.toLowerCase() });
}
export const evmWalletRequests = (page: Page) => page.evaluate(() => [...(window as unknown as { flofiDelegationRequests: string[] }).flofiDelegationRequests]);
export const SIGNING_METHODS = ['personal_sign', 'eth_signTypedData_v4', 'eth_sendTransaction', 'eth_sendRawTransaction', 'eth_signTransaction'];
