// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';
import { installSupplyWallet } from './supply-fixtures';

test('boxed wallet preserves connect/disconnect and aligns with the Settings toggle', async ({ page }) => {
  await installSupplyWallet(page, { connected: false });
  await page.goto('/');
  const header = page.getByRole('banner');
  const wallet = header.getByRole('group', { name: 'Wallet connection', exact: true });
  const settings = header.getByRole('button', { name: 'Settings', exact: true });
  await expect(wallet).toContainText('Wallet not connected');
  await expect(settings).toBeEnabled();
  await expect(settings).toHaveAttribute('aria-expanded', 'false');
  expect(await settings.innerText()).toBe('');
  await expect(settings.locator('svg')).toHaveCount(1);
  await settings.click();
  const options = header.getByRole('group', { name: 'Settings options', exact: true });
  await expect(options).toBeVisible();
  expect(await options.getByRole('button').allTextContents()).toEqual(['Language', 'Theme', 'Disconnect']);
  for (const option of await options.getByRole('button').all()) await expect(option).toBeDisabled();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('menu')).toHaveCount(0);
  await expect(wallet).toContainText('Wallet not connected');
  await settings.click();
  await expect(options).toHaveCount(0);
  await wallet.getByRole('button', { name: 'Connect Wallet', exact: true }).click();
  await expect(wallet).toContainText('Wallet: 0x1111…1111 · Base Sepolia');
  for (const width of [1440, 900, 390]) {
    await page.setViewportSize({ width, height: 900 });
    const walletBox = (await wallet.boundingBox())!;
    const settingsBox = (await settings.boundingBox())!;
    expect(Math.abs(walletBox.y + walletBox.height / 2 - settingsBox.y - settingsBox.height / 2)).toBeLessThan(1);
    expect(settingsBox.x).toBeGreaterThanOrEqual(walletBox.x + walletBox.width);
    expect(settingsBox.width).toBe(40);
    expect(settingsBox.height).toBe(40);
    expect(await wallet.evaluate(element => getComputedStyle(element).borderTopStyle)).toBe('solid');
    expect(await wallet.evaluate(element => parseFloat(getComputedStyle(element).borderRadius))).toBeGreaterThan(0);
    await expect(wallet.getByRole('button', { name: 'Disconnect', exact: true })).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  }
  await settings.click();
  await expect(options.getByRole('button', { name: 'Language', exact: true })).toBeVisible();
  await expect(options.getByRole('button', { name: 'Theme', exact: true })).toBeVisible();
  await expect(options.getByRole('button', { name: 'Disconnect', exact: true })).toBeEnabled();
  await options.getByRole('button', { name: 'Disconnect', exact: true }).click();
  await expect(options).toHaveCount(0);
  await expect(settings).toBeFocused();
  await expect(wallet).toContainText('Wallet not connected');
  await expect(wallet.getByRole('button', { name: 'Connect Wallet', exact: true })).toBeVisible();
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
});

test('Settings toggles without layout changes, closes outside/Escape/Tab and leaves wallet and node selection untouched', async ({ page }) => {
  await installSupplyWallet(page);
  await page.goto('/');
  await page.getByRole('button', { name: 'Add supply', exact: true }).click();
  const settings = page.getByRole('button', { name: 'Settings', exact: true });
  const options = page.getByRole('group', { name: 'Settings options', exact: true });
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 });
    const headerBefore = await page.getByRole('banner').boundingBox();
    const canvasBefore = await page.getByRole('region', { name: 'Workflow canvas', exact: true }).boundingBox();
    await settings.click();
    await expect(settings).toHaveAttribute('aria-expanded', 'true');
    await expect(options).toBeVisible();
    const gearBox = (await settings.boundingBox())!;
    const menuBox = (await options.boundingBox())!;
    expect(Math.abs(menuBox.x + menuBox.width - gearBox.x - gearBox.width)).toBeLessThan(1);
    expect(menuBox.y - gearBox.y - gearBox.height).toBe(8);
    expect(await page.getByRole('banner').boundingBox()).toEqual(headerBefore);
    expect(await page.getByRole('region', { name: 'Workflow canvas', exact: true }).boundingBox()).toEqual(canvasBefore);
    const disconnect = options.getByRole('button', { name: 'Disconnect', exact: true });
    await expect(disconnect).toBeEnabled();
    await expect(page.getByRole('group', { name: 'Wallet connection' })).toContainText('0x1111…1111');
    await settings.press('Escape');
    await expect(options).toHaveCount(0);
    await expect(settings).toBeFocused();
    await expect(page.locator('.flow-card.active')).toHaveCount(1);
    await settings.press('Enter');
    await expect(options).toBeVisible();
    await page.getByRole('heading', { name: 'Copilot', exact: true }).click();
    await expect(options).toHaveCount(0);
    await settings.click();
    await settings.press('Tab');
    await expect(disconnect).toBeFocused();
    await expect(options).toBeVisible();
    await disconnect.press('Tab');
    await expect(options).toHaveCount(0);
    await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '1');
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  }
});

test('advanced setup has a single outer expansion and retains existing forms and workflow checks', async ({ page }) => {
  await installSupplyWallet(page);
  await page.goto('/');
  await expect(page.getByText('Technical authoring tools', { exact: true })).toHaveCount(0);
  const advanced = page.locator('details.library[aria-label="Advanced action setup"]');
  await expect(advanced).toHaveCount(1);
  expect(await advanced.evaluate(element => element.parentElement?.closest('details') !== null)).toBe(false);
  await expect(advanced).not.toHaveAttribute('open');
  await page.getByRole('button', { name: 'Add swap', exact: true }).click();
  await expect(page.locator('.flow-card')).toHaveCount(1);
  const findings = advanced.getByRole('region', { name: 'Deterministic review findings' });
  await expect(findings).toBeHidden();
  await advanced.locator(':scope > summary').click();
  await expect(advanced).toHaveAttribute('open', '');
  await expect(findings).toBeVisible();
  await expect(advanced.getByRole('form', { name: 'Create swap proposal', exact: true })).toBeVisible();
  await expect(advanced.getByRole('form', { name: 'Create direct Across bridge proposal', exact: true })).toBeVisible();
  await advanced.getByText('Workflow IR', { exact: true }).click();
  const before = await findings.locator('[data-workflow-ir]').innerText();
  const revision = await page.locator('.summary-bar').getAttribute('data-workflow-revision');
  await advanced.locator(':scope > summary').click();
  await expect(findings).toBeHidden();
  await advanced.locator(':scope > summary').click();
  await expect(findings).toBeVisible();
  expect(await findings.locator('[data-workflow-ir]').innerText()).toBe(before);
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', revision!);
  expect(JSON.parse(before).nodes.some((node: { actionType: string }) => node.actionType === 'asset.swap.exact-input')).toBe(true);
});
