// SPDX-License-Identifier: AGPL-3.0-only
import { test,expect } from './fixtures';
import type { Page } from '@playwright/test';
import { installLendingWallet,lendingRpc,lendingSends,resetLending,LENDING_OWNER } from './lending-fixtures';
const panel=(page:Page)=>page.getByRole('region',{name:'Lending composition'});
async function author(page:Page,options:Parameters<typeof installLendingWallet>[1]={},chat=false){
  await installLendingWallet(page,options);await page.goto('/');
  if(chat){await page.locator('#mock-prompt').fill(`compose supply 0.1 USDC to Aave then borrow 0.01 USDC then swap borrowed USDC to WETH on Base Sepolia slippage 50 bps owner ${LENDING_OWNER}`);await page.getByRole('button',{name:'Send',exact:true}).click();}
  else {await page.getByText('Advanced action setup',{exact:true}).click();const form=page.getByRole('form',{name:'Compose lending'});await expect(form).toContainText(LENDING_OWNER);await form.getByRole('button',{name:'Review lending proposal'}).click();}
  await page.getByRole('button',{name:'Apply proposal'}).click();await expect(page.locator('.react-flow__node[data-id="lending-borrow"]')).toContainText('Borrow');
  await page.getByRole('button',{name:'Continue to Simulate'}).click();
}
async function review(page:Page){await page.getByRole('button',{name:'Simulate lending composition',exact:true}).click();await expect(panel(page)).toContainText('Expected output:');await page.getByRole('button',{name:'Review lending composition',exact:true}).click();await page.getByRole('button',{name:'Accept composed Review'}).click();await expect(panel(page).getByRole('button',{name:'Execute pool approval',exact:true})).toBeEnabled();}
const execute=(page:Page,step:string)=>panel(page).getByRole('button',{name:`Execute ${step}`,exact:true}).click();
async function confirmed(page:Page,step:string){await execute(page,step);await expect(panel(page)).toContainText(`${step.toUpperCase().replaceAll(' ','_')}: reconciled`);}
test.beforeEach(async()=>{await resetLending();});
test.setTimeout(120_000);
test('Canvas composition, Review and five explicit owner calls prove the MOCKED economic outcome',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await author(page);await review(page);
  await expect(panel(page)).toContainText('Borrow / exact Swap input: 0.01 USDC');await expect(panel(page)).toContainText('Debt USDC');await expect(panel(page)).toContainText('Health factor');expect(await lendingSends(page)).toBe(0);
  for(const step of ['pool approval','supply','borrow','router approval','swap']){await execute(page,step);await expect(panel(page)).toContainText(`${step.toUpperCase().replaceAll(' ','_')}: reconciled`);}
  await expect(panel(page)).toContainText('MOCKED / RECONCILED');expect(await lendingSends(page)).toBe(5);
  const link=await page.getByRole('link',{name:'Download composed Evidence Bundle'}).getAttribute('href');const evidence=JSON.parse(decodeURIComponent(link!.split(',')[1]!));
  expect(evidence.bundle).toMatchObject({environment:'MOCKED',outcome:'RECONCILED'});expect(evidence.bundle.reconciliation.debt[0]).toMatchObject({amount:'10000'});expect(evidence.composedExecution.completed).toBe(true);
  const requests=await page.evaluate(()=>(window as unknown as {lendingRequests:{method:string;params:unknown[]}[]}).lendingRequests.filter(r=>r.method==='eth_sendTransaction'));
  expect(requests).toHaveLength(5);for(const r of requests)expect(r.params[0]).not.toHaveProperty('nonce');expect(errors).toEqual([]);
});
test('Chat produces the same finite graph and typed Borrow-to-Swap Review',async({page})=>{await author(page,{},true);await review(page);expect(await lendingSends(page)).toBe(0);await expect(panel(page)).toContainText('0xba50cd2a20f6da35d788639e581bca8d0b5d4d5f');await expect(panel(page)).toContainText('Borrow / exact Swap input: 0.01 USDC');});
for(const setting of ['poolAvailable','swapAvailable','simulationAvailable'])test(`complete path gate blocks ${setting} before any Supply request`,async({page})=>{await author(page);await review(page);await lendingRpc('MOCK_reset',[{[setting]:false}]);await execute(page,'pool approval');expect(await lendingSends(page)).toBe(0);await expect(panel(page).getByRole('status')).toBeVisible();});
test('unsafe health factor blocks read-only simulation',async({page})=>{await author(page);await lendingRpc('MOCK_reset',[{scaledDebt:'9000000',userConfig:'3'}]);await page.getByRole('button',{name:'Simulate lending composition',exact:true}).click();await expect(panel(page).getByRole('status')).toBeVisible();expect(await lendingSends(page)).toBe(0);});
test('wrong wallet chain blocks before owner submission',async({page})=>{await author(page,{chain:'0x1'});await review(page);await execute(page,'pool approval');await expect(panel(page)).toContainText('Switch your wallet to Base Sepolia');expect(await lendingSends(page)).toBe(0);});
test('price drift invalidates authority and requires fresh Simulate and Review',async({page})=>{await author(page);await review(page);await lendingRpc('MOCK_reset',[{price:'110000000'}]);await execute(page,'pool approval');await expect(panel(page)).toContainText('Review expired or the market changed');expect(await lendingSends(page)).toBe(0);await page.getByRole('button',{name:'Fresh Simulate and Review of remaining steps'}).click();await page.getByRole('button',{name:'Accept composed Review'}).click();await confirmed(page,'pool approval');expect(await lendingSends(page)).toBe(1);});
test('lost Borrow result reloads into observation-only recovery and never sends another Borrow',async({page})=>{
  await author(page,{uncertainAt:3});await review(page);await execute(page,'pool approval');await execute(page,'supply');await execute(page,'borrow');await expect(panel(page)).toContainText('SUBMISSION_RESULT_UNKNOWN');expect(await lendingSends(page)).toBe(3);
  await page.reload();await page.getByRole('navigation',{name:'Workflow stages'}).getByRole('button',{name:'Execute',exact:true}).click();await page.getByRole('button',{name:'Observe existing execution'}).click();await expect(panel(page)).toContainText('BORROW: reconciled');expect(await lendingSends(page)).toBe(0);await expect(panel(page)).toContainText('debt: 0.01 USDC');
});
test('downstream route loss after Borrow retains debt and requires explicit fresh continuation',async({page})=>{
  await author(page);await review(page);for(const step of ['pool approval','supply','borrow'])await confirmed(page,step);await lendingRpc('MOCK_patch',[{swapAvailable:false}]);await execute(page,'router approval');await expect(panel(page).getByRole('status')).toBeVisible();expect(await lendingSends(page)).toBe(3);await page.getByRole('button',{name:'Observe existing execution'}).click();await expect(panel(page)).toContainText('debt: 0.01 USDC');await expect(panel(page)).toContainText('Borrow has completed');await expect(panel(page)).toContainText('Partial execution evidence');
  await lendingRpc('MOCK_patch',[{swapAvailable:true}]);await page.getByRole('button',{name:'Fresh Simulate and Review of remaining steps'}).click();await page.getByRole('button',{name:'Accept composed Review'}).click();await confirmed(page,'router approval');await confirmed(page,'swap');expect(await lendingSends(page)).toBe(5);await expect(panel(page)).toContainText('MOCKED / RECONCILED');
});
test('wallet disconnect after handoff stays observation-only, including reload',async({page})=>{await author(page,{disconnectedAt:1});await review(page);await execute(page,'pool approval');await expect(panel(page)).toContainText('SUBMISSION_RESULT_UNKNOWN');await page.getByRole('button',{name:'Observe existing execution'}).click();expect(await lendingSends(page)).toBe(1);await expect(panel(page).getByRole('button',{name:'Execute pool approval',exact:true})).toHaveCount(0);});
test('minimum-output violation blocks before any owner request',async({page})=>{await author(page);await review(page);await lendingRpc('MOCK_patch',[{quoteBps:'9800'}]);await execute(page,'pool approval');await expect(panel(page)).toContainText('cannot meet the reviewed minimum output');expect(await lendingSends(page)).toBe(0);});
test('failed Swap retains USDC debt and router allowance without a second attempt',async({page})=>{await author(page,{revertAt:5});await review(page);for(const step of ['pool approval','supply','borrow','router approval'])await confirmed(page,step);await execute(page,'swap');await expect(panel(page)).toContainText('SWAP: REVERTED');await expect(panel(page)).toContainText('debt: 0.01 USDC');await expect(panel(page)).toContainText('router 0.01 USDC');expect(await lendingSends(page)).toBe(5);await page.getByRole('button',{name:'Observe existing execution'}).click();await expect(panel(page)).toContainText('MOCKED / DIVERGENT');expect(await lendingSends(page)).toBe(5);await expect(panel(page).getByRole('button',{name:'Execute swap',exact:true})).toHaveCount(0);});
test('duplicate Execute clicks submit one approval',async({page})=>{await author(page);await review(page);await panel(page).getByRole('button',{name:'Execute pool approval',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await expect(panel(page)).toContainText('POOL_APPROVAL: reconciled');expect(await lendingSends(page)).toBe(1);});
test('accepted economic edits retire prior authority until new simulation and Review',async({page})=>{await author(page);await review(page);await page.getByRole('navigation',{name:'Workflow stages'}).getByRole('button',{name:'Build',exact:true}).click();await page.locator('#mock-prompt').fill(`compose supply 0.1 USDC to Aave then borrow 0.02 USDC then swap borrowed USDC to WETH on Base Sepolia slippage 50 bps owner ${LENDING_OWNER}`);await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByRole('button',{name:'Apply proposal'}).click();await page.getByRole('navigation',{name:'Workflow stages'}).getByRole('button',{name:'Execute',exact:true}).click();await expect(panel(page)).toContainText('The workflow changed');await expect(panel(page).getByRole('button',{name:'Execute pool approval',exact:true})).toHaveCount(0);expect(await lendingSends(page)).toBe(0);});
