// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';

test('Simulate anchors its CTAs inside the canvas beside the zoom controls', async ({ page }) => {
  await page.goto('/');
  const stages = page.getByRole('navigation', { name: 'Workflow stages' });
  await page.getByRole('button', { name: 'Rename workflow', exact: true }).click();
  await page.getByRole('textbox', { name: 'Workflow name', exact: true }).fill('ESPARTACUS');
  await page.getByRole('textbox', { name: 'Workflow name', exact: true }).press('Enter');
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
  await stages.getByRole('button', { name: 'Simulate', exact: true }).click();
  const panel = page.getByRole('region', { name: 'Workflow simulation workspace' });
  const graph = panel.getByRole('region', { name: 'Simulation workflow graph', exact: true });
  const summary = panel.getByRole('complementary', { name: 'Simulation Summary', exact: true });
  const returnToBuild = graph.getByRole('button', { name: 'Back to Build', exact: true });
  const reviewSwap = summary.getByRole('button', { name: 'Review swap', exact: true });
  const technical = panel.locator('.simulation-technical');
  await expect(graph).toBeVisible();
  await expect(panel.locator('.canvas-head').getByRole('heading', { name: 'ESPARTACUS', exact: true })).toBeVisible();
  await expect(panel.locator('.canvas-head')).not.toContainText(/mock|read-only|synthetic/i);
  await expect(panel.locator('.canvas-head').getByRole('heading', { name: 'Graph', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Back to Build', exact: true })).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Review swap', exact: true })).toHaveCount(0);
  await expect(reviewSwap).toHaveCount(0);
  await expect(page.locator('.summary-bar').getByRole('button', { name: 'Review swap', exact: true })).toHaveCount(0);
  await expect(panel.getByText('SIMULATE', { exact: true })).toHaveCount(0);
  await expect(panel.getByRole('heading', { name: 'Simulation', exact: true })).toHaveCount(0);
  await expect(panel.locator(':scope > .simulate-note, :scope > .simulate-details-toggle')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Show technical details', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Hide technical details', exact: true })).toHaveCount(0);
  await expect(page.getByText('Add a Base swap in Build before generating mocked artifacts.', { exact: true })).toBeHidden();
  await technical.locator(':scope > summary').click();
  await expect(panel.getByRole('button', { name: 'Generate mocked artifacts for revision 0', exact: true })).toBeDisabled();
  await technical.locator(':scope > summary').click();
  await expect(page.getByRole('region', { name: 'Base read-only observation' })).toBeHidden();
  await expect(page.getByRole('region', { name: 'Local fork Mode A simulation' })).toBeHidden();
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await expect(graph).toHaveAttribute('data-viewport', 'fitted');
    const graphBox = (await graph.boundingBox())!;
    const summaryBox = (await summary.boundingBox())!;
    const controlsBox = (await graph.locator('.react-flow__controls').boundingBox())!;
    const actionsBox = (await graph.locator('.simulation-canvas-actions').boundingBox())!;
    expect(actionsBox.x + actionsBox.width + 8).toBeLessThanOrEqual(controlsBox.x);
    expect(actionsBox.y + actionsBox.height + 16).toBeLessThanOrEqual(graphBox.y + graphBox.height);
    if (width === 1440) expect(summaryBox.x).toBeGreaterThan(graphBox.x + graphBox.width);
    else expect(summaryBox.y).toBeGreaterThanOrEqual(graphBox.y + graphBox.height);
    expect(controlsBox.x).toBeGreaterThan(graphBox.x);
    expect(controlsBox.y).toBeGreaterThan(graphBox.y);
    expect((await technical.boundingBox())!.y).toBeGreaterThanOrEqual(Math.max(graphBox.y + graphBox.height, summaryBox.y + summaryBox.height));
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  }
  await returnToBuild.click();
  await expect(stages.getByRole('button', { name: 'Build', exact: true })).toHaveAttribute('aria-current', 'page');
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(page.getByRole('heading', { name: 'ESPARTACUS', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Rename workflow', exact: true }).click();
  await page.getByRole('textbox', { name: 'Workflow name', exact: true }).fill('ETH Carry Strategy');
  await page.getByRole('textbox', { name: 'Workflow name', exact: true }).press('Enter');
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '0');
  await page.getByLabel('Describe your flow').fill('swap 2.25 USDC to WETH on Base slippage 50 bps');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await page.getByRole('button', { name: 'Apply proposal', exact: true }).click();
  await page.getByRole('button', { name: 'Simular Fees', exact: true }).click();
  await expect(panel.locator('.canvas-head').getByRole('heading', { name: 'ETH Carry Strategy', exact: true })).toBeVisible();
  await expect(graph).toHaveAttribute('data-viewport', 'fitted');
  await expect(graph.locator('.flow-card')).toBeInViewport();
  const viewport = graph.locator('.react-flow__viewport');
  const beforeZoom = await viewport.getAttribute('style');
  await graph.locator('.react-flow__controls-zoomout').click();
  await expect(viewport).not.toHaveAttribute('style', beforeZoom!);
  const afterZoom = await viewport.getAttribute('style');
  await graph.locator('.react-flow__controls-zoomin').click();
  await expect(viewport).not.toHaveAttribute('style', afterZoom!);
  await graph.locator('.react-flow__controls-fitview').click();
  await expect(graph.locator('.flow-card')).toBeInViewport();
  await technical.locator(':scope > summary').click();
  await panel.getByRole('button', { name: 'Generate mocked artifacts for revision 1', exact: true }).click();
  await expect(panel.locator('.simulate-swap')).toBeVisible();
  await expect(panel.locator('.simulate-swap')).toContainText('2.25 USDC');
  await expect(panel.locator('.chain-strip')).toBeVisible();
  await expect(reviewSwap).toHaveCount(0);
  await expect(technical).toHaveAttribute('data-technical-open', 'true');
  await expect(panel.locator('.chain-strip')).toBeVisible();
  await expect(page.getByRole('region', { name: 'Base read-only observation' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Local fork Mode A simulation' })).toBeVisible();
  const jsonButton = panel.getByRole('button', { name: 'Show JSON · Artifact Set', exact: true });
  await jsonButton.click();
  const proof = await panel.locator('[data-artifact-json="artifact-set"]').innerText();
  expect(JSON.parse(proof)).toBeTruthy();
  await technical.locator(':scope > summary').click();
  await expect(technical).toHaveAttribute('data-technical-open', 'false');
  await expect(page.getByRole('region', { name: 'Base read-only observation' })).toBeHidden();
  await returnToBuild.click();
  await expect(page.getByRole('heading', { name: 'ETH Carry Strategy', exact: true })).toBeVisible();
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '1');
  await expect(page.locator('.flow-card')).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Review swap', exact: true })).toHaveCount(0);
});
