// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect } from './fixtures';
import { installSupplyWallet } from './supply-fixtures';

test('Simulate and Execute open directly on existing content without a workspace introduction', async ({ page }) => {
  await installSupplyWallet(page);
  await page.goto('/');
  const nav = page.getByRole('navigation', { name: 'Workflow stages' });
  const execution = page.getByRole('main', { name: 'Execution workspace', exact: true });
  await nav.getByRole('button', { name: 'Execute', exact: true }).click();
  await expect(execution).toBeVisible();
  await expect(execution.locator('.workspace-heading, .workflow-context, .page-heading, .stage-current, .stage-guidance, #workspace-title')).toHaveCount(0);
  await expect(execution.getByRole('heading', { name: 'Execute', exact: true })).toHaveCount(0);
  expect(await execution.innerText()).not.toMatch(/Draft · Untitled workflow|EXECUTE \/ WORKFLOW|Current stage · Execute|Authorize and track execution|No chain selected|Revision 0/);
  await expect(execution.locator(':scope > :first-child')).toHaveAttribute('aria-label', 'Workflow overview');
  await expect(execution.getByRole('region', { name: 'Workflow overview graph', exact: true })).toBeVisible();
  await expect(execution.locator('.stage-empty, .unavailable')).toHaveCount(0);
  await expect(execution.getByRole('button', { name: 'Return to Build', exact: true })).toHaveCount(0);
  await expect(execution.getByRole('region', { name: 'Execute unavailable', exact: true })).toHaveCount(0);
  await execution.locator('.technical-workspace > summary').click();
  await expect(execution.getByText('A supported workflow, current simulation and explicit wallet authorization are required before execution.', { exact: true })).toBeVisible();
  await nav.getByRole('button', { name: 'Simulate', exact: true }).click();
  const main = page.getByRole('main', { name: 'Simulation workspace', exact: true });
  await expect(main).toBeVisible();
  await expect(main.locator('.workspace-heading, .workflow-context, .page-heading, .stage-current, .stage-guidance, #workspace-title')).toHaveCount(0);
  await expect(main.getByRole('region', { name: 'Simulation workflow graph', exact: true })).toBeVisible();
  await expect(main.getByRole('heading', { name: 'Prepare your workflow', exact: true })).toHaveCount(0);
  await expect(main.locator(':scope > :first-child')).toHaveAttribute('aria-label', 'Workflow simulation details');
  await nav.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Add supply', exact: true }).click();
  await page.getByRole('button', { name: 'Simular Fees', exact: true }).click();
  await expect(main).toBeVisible();
  await expect(main.locator('.workspace-heading, .workflow-context, .page-heading, .stage-current, .stage-guidance, #workspace-title')).toHaveCount(0);
  expect(await main.innerText()).not.toMatch(/Draft · Untitled workflow|SIMULATE \/ WORKFLOW|Current stage · Simulate|Understand the outcome|No chain selected/);
  await expect(main.getByRole('button', { name: 'Simulate Supply', exact: true })).toBeVisible();
  await expect(main.locator(':scope > :first-child')).toHaveAttribute('aria-label', 'Workflow simulation');
  await expect(main.getByRole('region', { name: 'Aave Supply', exact: true })).toBeVisible();
  await expect(main.getByRole('region', { name: 'Simulation workflow graph', exact: true }).getByRole('button', { name: 'Review Supply', exact: true })).toBeDisabled();
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '1');
  await nav.getByRole('button', { name: 'Execute', exact: true }).click();
  await expect(execution).toBeVisible();
  await expect(execution.locator('.workspace-heading, .workflow-context, .page-heading, .stage-current, .stage-guidance, #workspace-title')).toHaveCount(0);
  await expect(execution.getByRole('heading', { name: 'Execute', exact: true })).toHaveCount(0);
  expect(await execution.innerText()).not.toMatch(/Draft · Untitled workflow|EXECUTE \/ WORKFLOW|Current stage · Execute|Authorize and track execution|No chain selected|Revision 0/);
  await expect(execution.locator(':scope > :first-child')).toHaveAttribute('aria-label', 'Aave Supply');
  await expect(execution.getByRole('heading', { name: 'Review Supply', exact: true })).toBeVisible();
  await expect(execution.getByRole('button', { name: 'Accept Supply review', exact: true })).toHaveCount(0);
  await expect(execution.getByRole('button', { name: /^(Execute|Execute Supply)$/ })).toHaveCount(0);
  await nav.getByRole('button', { name: 'Build', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your Workflow', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Simular Fees', exact: true })).toBeVisible();
  await expect(page.locator('.flow-card.active')).toHaveCount(1);
  await expect(page.locator('.summary-bar')).toHaveAttribute('data-workflow-revision', '1');
});
