// SPDX-License-Identifier: AGPL-3.0-only
export type LandingLocale = 'pt' | 'en';

const en = {
  pageTitle: 'FloFi | Many ways in. One clear path.',
  pageDescription: "Bring swaps, bridges and lending into one clear crypto workflow. Compose with FloFi, review the details, and stay in control with your own wallet.",
  language: 'Language',
  mainNavigation: 'Main navigation',
  footerNavigation: 'Footer navigation',
  brandHome: 'FloFi home',
  skip: 'Skip to content',
  navProduct: 'Product',
  navNetworks: 'Networks',
  networksEyebrow: 'CONNECTED ECOSYSTEMS',
  networksTitle: 'Supported networks',
  networksBody: 'Compose across EVM and Solana ecosystems, with your assets and permissions in view.',
  networksNote: 'Network support varies by action. FloFi checks workflow availability and authorization requirements before you proceed.',
  tempoStatus: 'Upcoming',
  navSolutions: 'Solutions',
  navDevelopers: 'Developers',
  navDocs: 'Docs',
  navAbout: 'About',
  launch: 'Launch FloFi',
  buildWith: 'Build with FloFi',
  exploreDocs: 'Explore Docs',
  sourceCode: 'Source code',
  license: 'License',
  heroEyebrow: 'NON-CUSTODIAL · MULTICHAIN DEFI',
  heroTitleFirst: 'Financial intent,',
  heroTitleSecond: 'made',
  heroTitleAccent: 'executable.',
  heroBody: 'Compose DeFi workflows through conversation or a visual builder. Simulate supported actions, review permissions and a Strategy Manifest, then explicitly authorize execution with your own wallet.',
  heroFootnote: "Your crypto. Your workflow. Your wallet.",
  illustrativeScenario: 'Workflow example',
  futureScenario: 'Coming next · workflow example',
  scenariosEyebrow: "YOUR CRYPTO, CONNECTED",
  scenariosTitle: "One intent. Many possibilities.",
  scenariosBody: "Trade, move assets and plan your next step across familiar DeFi ecosystems.",
  scenariosNote: 'Explore these workflow examples with real assets and ecosystems. Available actions vary by network; recurring purchases and broader multichain composition are coming next.',
  scenarioSwap: "Swap ETH for USDC",
  scenarioSwapBody: "Turn a trade into a clear path with amounts and slippage you can review.",
  scenarioBridge: "Move USDC across networks",
  scenarioBridgeBody: "Plan a bridge from Base to Arbitrum with both sides in view.",
  scenarioLending: "Supply ETH. Borrow USDC.",
  scenarioLendingBody: "See collateral, borrowing limits and permissions together before you sign.",
  scenarioBitcoin: "Plan a recurring BTC purchase",
  scenarioBitcoinBody: "Explore a regular purchase strategy. Native BTC and wrapped BTC stay distinct.",
  scenarioBitcoinContext: "Bitcoin · WBTC on Ethereum · future strategy",
  scenarioMultichain: "Compose beyond one chain",
  scenarioMultichainBody: 'Plan connected SOL, USDC and ETH steps in a single reviewable workflow.',
  showcaseSwap: "Swap ETH → USDC",
  showcaseBridge: "Bridge USDC",
  quotePending: "Quote required",
  productIllustration: 'Product illustration',
  tabBuild: 'Build',
  tabSimulate: 'Simulate',
  tabExecute: 'Execute',
  workflowLabel: 'WORKFLOW',
  workflowUntitled: "Swap & bridge",
  workflowHint: 'Arrange your steps, then review the details.',
  intentCaptured: 'Intent captured',
  strategyPending: 'Strategy pending',
  assistantLabel: 'ASSISTANT',
  copilot: 'Copilot',
  startIntent: 'START WITH AN INTENT',
  whatDo: 'What do you want to do?',
  sampleIntent: "Swap ETH to USDC on Base, then bridge USDC to Arbitrum.",
  exploring: 'Exploring possible strategies…',
  stageIntent: 'Intent',
  stageStrategy: 'Strategy',
  stageReview: 'Review',
  stageExecute: 'Execute',
  stageVerify: 'Verify',
  storyEyebrow: 'HOW IT WORKS',
  storyTitleFirst: 'Many ways in.',
  storyTitleSecond: 'One clear path.',
  storyBody: 'Build your workflow. Review the details. Sign when you’re ready.',
  storyBuild: 'BUILD',
  storyReview: 'REVIEW',
  storyExecute: 'EXECUTE',
  storyBuildTitle: 'Build your way.',
  storyBuildBody: 'Start from chat, canvas, or a connected channel.',
  storyBuildModel: 'One shared workflow',
  storyBuildNote: 'Your intent, structured in FloFi.',
  storyReviewTitle: 'Know before you sign.',
  storyReviewBody: 'Review permissions, limits, and execution intent.',
  storySimulation: 'Simulation',
  storyPermissions: 'Permissions',
  storyLimits: 'Limits',
  storyApproval: 'Your explicit approval',
  storyReviewNote: 'Changes require a fresh review.',
  storyExecuteTitle: 'Your wallet. Your call.',
  storyExecuteBody: 'Sign with your wallet, execute, and follow the result.',
  storySignature: 'Your wallet signature',
  storyRun: 'Workflow execution',
  storyResult: 'Tracking & reconciliation',
  storyExecuteNote: 'Check the result against what you approved.',
  reviewTitle: 'Review before you authorize',
  reviewSubtitle: 'See the material parameters before requesting a signature.',
  reviewAuthorizeStage: 'Authorize',
  reviewSwap: "ETH → USDC swap",
  intentAmount: "Example input amount",
  intentAmountValue: "0.5 ETH",
  finalAmountHint: 'Final amount is set by a fresh review.',
  networkCost: 'Network cost',
  freshEstimate: 'Fresh estimate',
  priceRange: "Minimum received",
  setAtReview: 'Set at review',
  maximumSlippage: 'Maximum slippage',
  boundedAtReview: 'Bounded at review',
  assetsInvolved: 'Assets involved',
  reviewAssets: "ETH · USDC",
  positionRange: "Review the route",
  lowerBound: "Input asset",
  currentPrice: "Quote required",
  upperBound: "Output asset",
  whatCanChange: 'What can change',
  riskRange: "The quoted exchange rate can change.",
  riskFees: 'Fees depend on market activity.',
  riskConditions: 'Execution conditions may change before signing.',
  reviewNotice: 'Any changed transaction parameters require a fresh review.',
  authorizingScope: "Review this exact workflow before signing.",
  walletInBuilder: 'Your wallet. Your explicit approval.',
  authorizeWorkflow: 'Authorize workflow',
  clarityEyebrow: 'BUILT FOR CLARITY',
  clarityTitle: 'See the operation before it becomes a transaction.',
  clarityBody: 'FloFi makes supported DeFi actions understandable before authorization, including assets, limits, costs, risks and approval scope.',
  clarityFollowup: 'After execution, FloFi reconciles the observed result with what was authorized on supported paths.',
  structured: 'Structured',
  structuredBody: 'Complex actions become a clear financial workflow.',
  reviewable: 'Reviewable',
  reviewableBody: 'Material parameters are visible before authorization.',
  verifiable: 'Verifiable',
  verifiableBody: 'The onchain result can be compared with what was approved.',
  buildersEyebrow: 'FOR BUILDERS',
  buildersTitleFirst: 'Build financial experiences',
  buildersTitleSecond: 'without rebuilding DeFi infrastructure.',
  buildersBody: "Explore FloFi's Developer API, TypeScript SDK and MCP to bring a shared workflow model into your app. Users review permissions and sign in FloFi with their own wallet.",
  diagramWallet: 'Wallet',
  diagramApp: 'App',
  diagramAgent: 'Agent',
  diagramProtocols: 'Onchain protocols',
  executionInfrastructure: 'Execution infrastructure',
  diagramAuthorization: 'Authorization',
  diagramVerification: 'Verification',
  ecosystemDirection: 'Roadmap · broader protocol coverage',
  more: 'More networks and protocols',
  oneIntegration: 'One workflow model. Multiple entry points.',
  partnerBody: 'API keys and AI proposals carry no financial authority. Explore integration availability and setup in the documentation.',
  uxYours: 'Your UX stays yours',
  uxYoursBody: 'A partner can keep its own interface and user relationship.',
  executionStructured: 'Execution stays structured',
  executionStructuredBody: 'FloFi only runs supported workflows.',
  outcomesInspectable: 'Outcomes stay inspectable',
  outcomesInspectableBody: 'Recorded executions can be checked and reconciled.',
  developerDocs: 'Developer documentation',
  developerDocsBody: 'Explore the API, SDK, webhooks and workflow guides. Find the integration options and access requirements for your app.',
  openBuilder: 'Open FloFi',
  visionEyebrow: 'THE ROAD AHEAD',
  visionTitleFirst: 'Agents can understand intent.',
  visionTitleSecond: 'FloFi makes it executable.',
  visionBody: "A trade, a bridge, a lending strategy. The direction is one clear workflow across your crypto, with FloFi as an execution layer behind wallets, dapps and intelligent agents. Broader coverage remains on the roadmap.",
  visionFootnote: 'From financial intent to verifiable onchain execution.',
  executionLayer: 'Execution layer',
  onchainFinance: 'Onchain finance',
  footerLine: 'Built for programmable finance.',
};

const pt: Record<keyof typeof en, string> = {
  pageTitle: 'FloFi | Várias entradas. Um caminho claro.',
  pageDescription: "Reúna swaps, bridges e empréstimos em um fluxo cripto claro. Crie com FloFi, revise os detalhes e mantenha o controle com sua carteira.",
  language: 'Idioma',
  mainNavigation: 'Navegação principal',
  footerNavigation: 'Navegação do rodapé',
  brandHome: 'Página inicial FloFi',
  skip: 'Ir para o conteúdo',
  navProduct: 'Produto',
  navNetworks: 'Redes',
  networksEyebrow: 'ECOSSISTEMAS CONECTADOS',
  networksTitle: 'Redes compatíveis',
  networksBody: 'Crie fluxos em ecossistemas EVM e Solana, com seus ativos e permissões à vista.',
  networksNote: 'O suporte de rede varia por ação. O FloFi verifica a disponibilidade do fluxo e os requisitos de autorização antes de você prosseguir.',
  tempoStatus: 'Em breve',
  navSolutions: 'Soluções',
  navDevelopers: 'Desenvolvedores',
  navDocs: 'Docs',
  navAbout: 'Sobre',
  launch: 'Abrir FloFi',
  buildWith: 'Construir com FloFi',
  exploreDocs: 'Explorar Docs',
  sourceCode: 'Código-fonte',
  license: 'Licença',
  heroEyebrow: 'DEFI MULTICHAIN · NÃO CUSTODIAL',
  heroTitleFirst: 'Intenção financeira,',
  heroTitleSecond: 'agora',
  heroTitleAccent: 'executável.',
  heroBody: 'Crie fluxos DeFi por conversa ou no construtor visual. Simule ações compatíveis, revise permissões e o Strategy Manifest e autorize a execução explicitamente com sua carteira.',
  heroFootnote: "Seus ativos. Seu fluxo. Sua carteira.",
  illustrativeScenario: 'Exemplo de fluxo',
  futureScenario: 'Em breve · exemplo de fluxo',
  scenariosEyebrow: "SEUS ATIVOS, CONECTADOS",
  scenariosTitle: "Uma intenção. Muitas possibilidades.",
  scenariosBody: "Negocie, mova ativos e planeje o próximo passo em ecossistemas DeFi conhecidos.",
  scenariosNote: 'Explore estes exemplos com ativos e ecossistemas reais. As ações disponíveis variam por rede; compras recorrentes e composições multichain mais amplas vêm a seguir.',
  scenarioSwap: "Troque ETH por USDC",
  scenarioSwapBody: "Transforme uma troca em um caminho claro, com valores e slippage que você pode revisar.",
  scenarioBridge: "Mova USDC entre redes",
  scenarioBridgeBody: "Planeje um bridge da Base para Arbitrum com os dois lados à vista.",
  scenarioLending: "Forneça ETH. Tome USDC.",
  scenarioLendingBody: "Veja garantias, limites de empréstimo e permissões antes de assinar.",
  scenarioBitcoin: "Planeje compras recorrentes de BTC",
  scenarioBitcoinBody: "Explore uma estratégia de compras regulares. BTC nativo e wrapped BTC continuam distintos.",
  scenarioBitcoinContext: "Bitcoin · WBTC na Ethereum · estratégia futura",
  scenarioMultichain: "Crie além de uma única rede",
  scenarioMultichainBody: 'Planeje etapas conectadas de SOL, USDC e ETH em um único fluxo revisável.',
  showcaseSwap: "Trocar ETH → USDC",
  showcaseBridge: "Bridge de USDC",
  quotePending: "Cotação necessária",
  productIllustration: 'Ilustração do produto',
  tabBuild: 'Criar',
  tabSimulate: 'Simular',
  tabExecute: 'Executar',
  workflowLabel: 'FLUXO',
  workflowUntitled: "Swap & bridge",
  workflowHint: 'Organize as etapas e depois revise os detalhes.',
  intentCaptured: 'Intenção registrada',
  strategyPending: 'Estratégia pendente',
  assistantLabel: 'ASSISTENTE',
  copilot: 'Copilot',
  startIntent: 'COMECE COM UMA INTENÇÃO',
  whatDo: 'O que você quer fazer?',
  sampleIntent: "Troque ETH por USDC na Base e faça um bridge de USDC para Arbitrum.",
  exploring: 'Explorando estratégias possíveis…',
  stageIntent: 'Intenção',
  stageStrategy: 'Estratégia',
  stageReview: 'Revisão',
  stageExecute: 'Execução',
  stageVerify: 'Verificação',
  storyEyebrow: 'COMO FUNCIONA',
  storyTitleFirst: 'Várias entradas.',
  storyTitleSecond: 'Um caminho claro.',
  storyBody: 'Crie seu fluxo. Revise os detalhes. Assine quando estiver pronto.',
  storyBuild: 'CRIAR',
  storyReview: 'REVISAR',
  storyExecute: 'EXECUTAR',
  storyBuildTitle: 'Crie do seu jeito.',
  storyBuildBody: 'Comece pelo chat, canvas ou um canal conectado.',
  storyBuildModel: 'Um único fluxo FloFi',
  storyBuildNote: 'Sua intenção, organizada no FloFi.',
  storyReviewTitle: 'Entenda antes de assinar.',
  storyReviewBody: 'Revise permissões, limites e a intenção da execução.',
  storySimulation: 'Simulação',
  storyPermissions: 'Permissões',
  storyLimits: 'Limites',
  storyApproval: 'Sua aprovação explícita',
  storyReviewNote: 'Mudanças exigem uma nova revisão.',
  storyExecuteTitle: 'Sua carteira. Sua decisão.',
  storyExecuteBody: 'Assine com sua carteira, execute e acompanhe o resultado.',
  storySignature: 'Assinatura da sua carteira',
  storyRun: 'Execução do fluxo',
  storyResult: 'Acompanhamento e reconciliação',
  storyExecuteNote: 'Confira o resultado com o que você aprovou.',
  reviewTitle: 'Revise antes de autorizar',
  reviewSubtitle: 'Confira os parâmetros relevantes antes de solicitar uma assinatura.',
  reviewAuthorizeStage: 'Autorizar',
  reviewSwap: "Swap ETH → USDC",
  intentAmount: "Valor de entrada ilustrativo",
  intentAmountValue: "0,5 ETH",
  finalAmountHint: 'O valor final é definido após uma nova revisão.',
  networkCost: 'Custo de rede',
  freshEstimate: 'Estimativa atualizada',
  priceRange: "Mínimo recebido",
  setAtReview: 'Definida na revisão',
  maximumSlippage: 'Slippage máximo',
  boundedAtReview: 'Limitado na revisão',
  assetsInvolved: 'Ativos envolvidos',
  reviewAssets: "ETH · USDC",
  positionRange: "Revise a rota",
  lowerBound: "Ativo de entrada",
  currentPrice: "Cotação necessária",
  upperBound: "Ativo de saída",
  whatCanChange: 'O que pode mudar',
  riskRange: "A taxa de câmbio cotada pode mudar.",
  riskFees: 'As taxas dependem da atividade do mercado.',
  riskConditions: 'As condições de execução podem mudar antes da assinatura.',
  reviewNotice: 'Qualquer parâmetro alterado exige uma nova revisão.',
  authorizingScope: "Revise exatamente este fluxo antes de assinar.",
  walletInBuilder: 'Sua carteira. Sua aprovação explícita.',
  authorizeWorkflow: 'Autorizar fluxo',
  clarityEyebrow: 'CLAREZA EM CADA ETAPA',
  clarityTitle: 'Veja a operação antes que ela vire uma transação.',
  clarityBody: 'FloFi torna ações DeFi compatíveis compreensíveis antes da autorização, incluindo ativos, limites, custos, riscos e escopo de aprovação.',
  clarityFollowup: 'Após a execução, FloFi reconcilia o resultado observado com o que foi autorizado nos caminhos compatíveis.',
  structured: 'Estruturado',
  structuredBody: 'Ações complexas se tornam um fluxo financeiro claro.',
  reviewable: 'Revisável',
  reviewableBody: 'Os parâmetros relevantes ficam visíveis antes da autorização.',
  verifiable: 'Verificável',
  verifiableBody: 'O resultado onchain pode ser comparado ao que foi aprovado.',
  buildersEyebrow: 'PARA QUEM CONSTRÓI',
  buildersTitleFirst: 'Crie experiências financeiras',
  buildersTitleSecond: 'sem reconstruir a infraestrutura DeFi.',
  buildersBody: 'Explore a Developer API, o SDK TypeScript e o MCP do FloFi para integrar um modelo compartilhado de fluxos ao seu app. Os usuários revisam permissões e assinam no FloFi com sua própria carteira.',
  diagramWallet: 'Carteira',
  diagramApp: 'App',
  diagramAgent: 'Agente',
  diagramProtocols: 'Protocolos onchain',
  executionInfrastructure: 'Infraestrutura de execução',
  diagramAuthorization: 'Autorização',
  diagramVerification: 'Verificação',
  ecosystemDirection: 'Roadmap · maior cobertura de protocolos',
  more: 'Mais redes e protocolos',
  oneIntegration: 'Um modelo de fluxo. Múltiplos pontos de entrada.',
  partnerBody: 'Chaves de API e propostas de IA não têm autoridade financeira. Consulte a disponibilidade e a configuração das integrações na documentação.',
  uxYours: 'Sua experiência continua sua',
  uxYoursBody: 'O parceiro mantém sua interface e o relacionamento com o usuário.',
  executionStructured: 'Execução estruturada',
  executionStructuredBody: 'FloFi executa apenas fluxos compatíveis.',
  outcomesInspectable: 'Resultados inspecionáveis',
  outcomesInspectableBody: 'Execuções registradas podem ser conferidas e reconciliadas.',
  developerDocs: 'Documentação para desenvolvedores',
  developerDocsBody: 'Explore API, SDK, webhooks e guias de fluxos. Encontre as opções de integração e os requisitos de acesso para seu app.',
  openBuilder: 'Abrir FloFi',
  visionEyebrow: 'O PRÓXIMO PASSO',
  visionTitleFirst: 'Agentes entendem intenções.',
  visionTitleSecond: 'FloFi as torna executáveis.',
  visionBody: "Uma troca, um bridge, uma estratégia de empréstimo. A direção é um fluxo claro entre seus ativos, com FloFi como camada de execução por trás de carteiras, dapps e agentes inteligentes. A cobertura mais ampla continua no roadmap.",
  visionFootnote: 'Da intenção financeira à execução onchain verificável.',
  executionLayer: 'Camada de execução',
  onchainFinance: 'Finanças onchain',
  footerLine: 'Feito para finanças programáveis.',
};

export type LandingCopy = typeof en;
export const landingText: Record<LandingLocale, LandingCopy> = { en, pt };
