// SPDX-License-Identifier: AGPL-3.0-only
import Link from 'next/link';
import { ArticleFrame } from '../../components/docs/article';
import { DocsMascot } from '../../components/docs/docs-mascot';
import styles from '../../components/docs/docs.module.css';

const sections = [{ id: 'start-building', title: 'Start building' }, { id: 'the-workflow-lifecycle', title: 'The workflow lifecycle' }, { id: 'build-on-flofi', title: 'Build on FloFi' }];
export default function DocsHome() {
  return <ArticleFrame title="Documentation" group="Welcome to FloFi" description="Everything you need to turn intent into a workflow you can build, inspect and verify." sections={sections}>
    <div className={styles.homeHero}><div><span className={styles.heroTag}><span className={styles.statusDot}/>INTENT → EXECUTION</span><h2>Build with clarity.<br/><span>Execute with confidence.</span></h2><p>From your first workflow to a deeply integrated experience. Your decisions stay explicit, every step stays inspectable.</p><div className={styles.homeActions}><Link href="/docs/getting-started">Get started <span aria-hidden="true">→</span></Link><Link href="/docs/developer-api">Explore the API <span aria-hidden="true">↗</span></Link></div></div><DocsMascot/></div>
    <section className={styles.homeSection} aria-labelledby="start-building"><div className={styles.sectionHeading}><span className={styles.eyebrow}>YOUR NEXT STEP</span><h2 id="start-building">Start building</h2><p>A short path from an idea to an informed decision.</p></div><div className={styles.guideCards}>{([
      ['01', 'Your First Workflow', 'A practical walkthrough of build, simulate, review and verify.', '/docs/your-first-workflow'],
      ['02', 'Chat & Visual Builder', 'Two interfaces. One canonical workflow. Clear proposals.', '/docs/chat-visual-builder'],
      ['03', 'Supported Networks', 'Explore available paths and their exact evidence boundaries.', '/docs/supported-networks'],
    ] as const).map(([number, title, description, href]) => <Link key={href} href={href}><span>{number} <b aria-hidden="true">↗</b></span><h3>{title}</h3><p>{description}</p><small>Read guide →</small></Link>)}</div></section>
    <section className={styles.homeSection} aria-labelledby="the-workflow-lifecycle"><div className={styles.sectionHeading}><span className={styles.eyebrow}>THE FLOFI WAY</span><h2 id="the-workflow-lifecycle">A workflow you can trust, step by step.</h2><p>Every transition has a purpose. Authorization always stays with the owner.</p></div><div className={styles.lifecycle}>{([['Build', 'Make intent explicit.', '/docs/chat-visual-builder'], ['Simulate', 'Inspect before committing.', '/docs/simulation'], ['Review', 'Read the exact Manifest.', '/docs/strategy-manifest'], ['Authorize', 'Your wallet. Your decision.', '/docs/wallet-authorization'], ['Verify', 'Follow evidence, not assumptions.', '/docs/execution-verification']] as const).map(([title, description, href], i) => <Link href={href} key={href}><span>{i + 1}</span><div><strong>{title}</strong><p>{description}</p></div><b aria-hidden="true">→</b></Link>)}</div></section>
    <section className={styles.homeSection} aria-labelledby="build-on-flofi"><div className={styles.sectionHeading}><span className={styles.eyebrow}>FOR DEVELOPERS</span><h2 id="build-on-flofi">Your experience. FloFi’s workflow engine.</h2><p>Integrate structured intent and explicit owner handoffs into your product.</p></div><div className={styles.integrationCards}>{([['{ }', 'Developer API', 'Server-side sandbox capabilities, strategies and approval handoffs.', '/docs/developer-api'], ['TS', 'TypeScript SDK', 'A thin workspace client with safe retries and verified webhooks.', '/docs/typescript-sdk'], ['⌘', 'MCP Integrations', 'Structured tools for configured agent clients. No financial authority.', '/docs/mcp-integrations']] as const).map(([icon, title, description, href]) => <Link key={href} href={href}><span>{icon}</span><div><h3>{title}</h3><p>{description}</p></div><b aria-hidden="true">↗</b></Link>)}</div><div className={styles.homeBoundary}><strong>Understand the boundaries.</strong><p>Implementation, deployment availability and execution evidence are distinct. Start with <Link href="/docs/security">Security</Link> and <Link href="/docs/architecture">Architecture</Link>.</p></div></section>
    <footer className={styles.articleFooter}>Built with FloFi. Designed for decisions you can inspect.</footer>
  </ArticleFrame>;
}
